rvm:
- 2.0
- 2.1
- 2.2

sudo: true

env:
  global:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml

bundler_args: --without vagrant

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/master/scripts/start_docker.sh)

script:
- bundle exec rake integration:docker

after_failure: cat docker_daemon.log
